#!/bin/sh
#
prog=addmovie
usage="$prog [-s spf] [-f first_frame] [-n frame_count] [-F] title i1 i2 ..."
#
#	Add a movie named "name" to our catalog.  It consists of one or
#	more video files found relative to the current directory, and
#	concatentated together.
#
#	files, each of which may have additional information in a .data file.
#	All are processed into the catalog directory, if forced or the catalog
#	entry is missing or older.
#
#	Careful with those quotes: these titles usually contain spaces. Tabs
#	are our field separators.
#
#	-F	force rebuild of given movies

WEB_CATALOG=/r/media/slowmovies/catalog

#WRKDIR=${WRKDIR:-${TMPDIR}/${prog}}
#mkdir -p $WRKDIR        || exit 100
#trap "rm -rf $WRKDIR" EXIT

spf=10
start=0
count=all
force=

while [ $# -gt 0 ]
do
	case "$1" in
	-s)	shift; spf=$1; shift;;
	-f)	shift; start=$1; shift;;
	-F)	shift; force=true;;
	-n)	shift; count=$1; shift;;
	-*)	echo "$usage" 1>&2
		exit 1;;
	*)	break
	esac
done

if [ $# -lt 2 ]
then
	echo "$usage" 1>&2
	exit 1
fi

title="$1";	shift

inputlist=""
while [ $# -gt 0 ]
do
	inputlist="$inputlist -i $1"
	shift
done

cataloged_video="$WEB_CATALOG/$title"
video_info="$cataloged_video/info"

if [ ! -n "$force" -a -d "$cataloged_video" ]
then
	if [ ! -s "$video_info" ]
	then
		echo "Info missing rebuilding	$title ..." 1>&2
		rm -rf "$cataloged_video"
	else
		echo "Skipping	$title ..." 1>&2
		exit 0
	fi
fi

mkdir -p "$cataloged_video"

#rm -f "$video_info"

echo "Processing	$title ..." 1>&2
ffmpeg $inputlist -y -q:v 2 -v 16 -huffman optimal \
	-vf "drawtext=text='Through the Adirondacks': \
		fontcolor=white: fontsize=14: \
		box=1: boxcolor=black@0.5: \
		fix_bounds=1: \
		boxborderw=5: x=5: y=h-18:, \
	drawtext=text='frame %{n}': \
		fontcolor=white: fontsize=12: \
		box=1: boxcolor=black@0.5: \
		fix_bounds=1: \
		boxborderw=5: x=w-tw-5: y=h-14:" \
	"$cataloged_video/video.mp4" || {
		rm -rf "$cataloged_video"
		echo "	error, aborting" 1>&2
		exit 10
	}


# generate executable shell variables for relevant information

cat <<!EOF >"$video_info"
title='$title'
spf=$spf
start=$start
count=$count
updated=`date +%s`
!EOF
chmod +x "$video_info"

indexsm
