#!/bin/sh
#
prog=addmovie
usage="$prog [-s spf] [-f first_frame] [-n frame_count] [-F] [-q quality] title subtitle i1 i2 ..."
#
#	Add a movie named "name" to our catalog.  It consists of one or
#	more video files found relative to the current directory, and
#	concatentated together.
#
#	files, each of which may have additional information in a .data file.
#	All are processed into the catalog directory, if forced or the catalog
#	entry is missing or older.
#
#	Careful with those quotes: these titles usually contain spaces. Tabs
#	are our field separators.
#
#	-F	force rebuild of given movies

. slowdefs	|| exit 99

nspf=10
nfirst=0
ncount=all
nforce=
nquality=

while [ $# -gt 0 ]
do
	case "$1" in
	-s)	shift; nspf=$1; shift;;
	-f)	shift; nfirst=$1; shift;;
	-F)	shift; nforce=true;;
	-n)	shift; ncount=$1; shift;;
	-q)	shift; nquality=$1; shift;;
	-*)	echo "$usage" 1>&2
		exit 1;;
	*)	break
	esac
done

if [ $# -lt 3 ]
then
	echo "usage: $usage" 1>&2
	exit 1
fi

title="$1";	shift
subtitle="$1";	shift

inputlist=""
while [ $# -gt 0 ]
do
	inputlist="$inputlist -i $1"
	shift
done

mkdir -p "$MASTER_CATALOG_DIR/$title"
cd "$MASTER_CATALOG_DIR/$title"

if [ ! -s banner.png ]
then
	smbanner "$title" "$subtitle"  banner.png
fi

# generate executable shell variables for relevant information


if [ -n "$force" -o ! -s info -o ! -s video.mp4  ]
then
	echo "$prog:	$title		building ..." 1>&2
	#ffmpeg $inputlist -y -v 16  \
	ffmpeg $inputlist -y -q:v 2 -v 16 -huffman optimal \
		-vf "drawtext=text='$title': \
			fontcolor=white: fontsize=20: \
			box=1: boxcolor=black@0.5: \
			fix_bounds=1: \
			boxborderw=5: x=5: y=h-22:, \
		drawtext=text='frame %{n}': \
			fontcolor=white: fontsize=16: \
			box=1: boxcolor=black@0.5: \
			fix_bounds=1: \
			boxborderw=5: x=w-tw-5: y=h-18:" \
		video.mp4 || {
			rm -f info
			echo "	error, aborting" 1>&2
			exit 10
		}
	updated=`date +%s`
else
	echo "$prog:	$title		updating ..." 1>&2
	. ./info
fi

# generate new info file

cat <<!EOF >info
title='$title'
spf=$nspf
first=$nfirst
count=$ncount
quality=$nquality
!EOF
chmod +x info

set +x

indexsm

