#!/bin/sh
#
prog=createsm
usage="$prog [-F]"
#
#	(re)install all our movies, or the ones that are new or changed.
#
#	-F	force rebuild of all

force=
while [ $# -gt 0 ]
do
	case "$1" in
	-F)	shift; force="-F";;
	-*)	echo "$usage" 1>&2
		exit 1;;
	*)	break
	esac
done

if [ $# -gt 0 ]
then
	echo "$usage" 1>&2
	exit 1
fi

if [ -n "$force" ]
then
	cd /r/media/slowmovies/catalog	|| exit 10
	rm -f */info
	echo "$prog: all slow movies disabled" 1>&2
fi

SMSRC=/r/media/slowmovies/src
addsm -f 200 "NJ-approved firework"	$SMSRC/NJFireworksLarge.mp4
addsm "2011 fireworks"		$SMSRC/2011fireworks.mp4

SLOWSTAGE=$HOME/tmp/slowstage
./addsm -f 2 "Across the Sierras"	$SLOWSTAGE/AcrossTheSierras/*.mp4
./addsm "Asilomar"		$SLOWSTAGE/Asilomar/*.mp4
./addsm "Asilomar Beach"	$SLOWSTAGE/AsilomarBeach/*.mp4

# nice morning view:
./addsm "Basin and Range"	$SLOWSTAGE/BasinAndRange/*.mp4

# Needs to start at least after 41, 69 is goo
./addsm "Hana Road westbound"	$SLOWSTAGE/HanaRoadWB/*.avi

./addsm "It is flat"		$SLOWSTAGE/ItsFlat/*.mp4

# nice, but needs the slow header skipped
./addsm "Sacramento"		$SLOWSTAGE/NearSacramento/*.mp4
./addsm "Rockies Road"		$SLOWSTAGE/RockiesRoad/*.mp4
./addsm "Into Utah"		$SLOWSTAGE/ToUtah/*.mp4

TIME_LAPSE=$HOME/tmp/slowstage/timelapse
# long black frames at start:
./addsm "Through the Adirondacks"	$TIME_LAPSE/adirondacks.mov

#./addsm "At the beach"			$TIME_LAPSE/beach.mpg
./addsm "Bernardsville North"		$TIME_LAPSE/bville-north-clip.mov
./addsm "My Old Commute to FP"		$TIME_LAPSE/commute.mov
./addsm "Around Darien"			$TIME_LAPSE/darien.mov
./addsm "Ellivesdranreb"		$TIME_LAPSE/ellivsdranreb.mov
# boring, all cloudy
#./addsm "EWR to ORD test"		$TIME_LAPSE/ewr-ord-test.mov
./addsm "Go west"			$TIME_LAPSE/gowest.mov
# Needs higher res:
./addsm "East from Key West"		$TIME_LAPSE/key-west-east.mov
./addsm "East from Key West second"	$TIME_LAPSE/keys-eastbound.mov
# not very interesting
#./addsm "A lava lamp"			$TIME_LAPSE/lavalamp.mpeg
# poor video:
#./addsm "Moonrise in Nantucket"		$TIME_LAPSE/moonrise.mpeg
./addsm "ORD to SFO test"		$TIME_LAPSE/ord-sfo-test.mov
./addsm "Restroom"			$TIME_LAPSE/rest60.mpg
# a test, but not interesting:
#./addsm "Reverse"			$TIME_LAPSE/reverse.mov
./addsm "Slow"				$TIME_LAPSE/slow.mov
./addsm "Fast solitaire, slowly"	$TIME_LAPSE/solitaire.mov

ARCHIVES=$HOME/tmp/slowstage/archives
# really poor video, both seem identical
#./addsm -f 550 "Sand castle 0"			$ARCHIVES/castle0.mv
#./addsm "Sand castle 1"			$ARCHIVES/castle1.mv

# windowseat
WINDOWSEAT=$HOME/tmp/slowstage/windowseat/SFO-EWR
# not loaded yet
./addsm "SFO-EWR, the windowseat"	$WINDOWSEAT/GOPR2216.MP4 $WINDOWSEAT/GO0*

indexsm
