#!/bin/sh
#
prog=createsm
usage="$prog [-F]"
#
#	(re)install all our movies, or the ones that are new or changed.
#
#	-F	force rebuild of all

force=
while [ $# -gt 0 ]
do
	case "$1" in
	-F)	shift; force="-F";;
	-*)	echo "$usage" 1>&2
		exit 1;;
	*)	break
	esac
done

if [ $# -gt 0 ]
then
	echo "$usage" 1>&2
	exit 1
fi

. slowdefs	|| exit 99

if [ -n "$force" ]
then
	cd $MASTER_CATALOG_DIR	|| exit 10
	rm -f */info
	echo "$prog: all slow movies disabled" 1>&2
fi

## surfside beach ##

addsm "Sand castle 1" \
	"Sand castle 1" \
		/r/media/videos/ACK/Surfside/castle-1/*.MP4

addsm "Sand castle 2" \
	"Sand castle 2" \
		/r/media/videos/ACK/Surfside/castle-2/*.MP4

addsm -s 3 "Surfside sunset" \
	"Surfside sunset" \
		/r/media/videos/ACK/Surfside/sunset-raw/*.MP4

addsm "Surfside beach pool 1" \
	"Surfside beach pool 1" \
		/r/media/videos/ACK/Surfside/wet-1.MP4

addsm "Surfside beach pool 2" \
	"Surfside beach pool 2" \
		/r/media/videos/ACK/Surfside/wet-2.MP4

addsm "Surfside beach pool 3" \
        "Surfside beach pool 3" \
                /r/media/videos/ACK/Surfside/wet-3/wet3-[ab].MP4

addsm -f 200 "NJ-approved firework" \
	"Now that fireworks are legal in NJ, we can watch one." \
		/r/media/videos/Fireworks/NJFireworksLarge.mp4

addsm "2011 fireworks" \
	"A fireworks display from 2011 at the Somerset Hills Gold course." \
		/r/media/videos/Fireworks/fireworks2011-[12].mp4

addsm "Mousecam" \
	"A mouse investigates a Have-A-Heart trap, under infrared lighting." \
		/r/media/videos/Etc/mousecam.mpg

SLOWSTAGE=$HOME/tmp/slowstage

addsm -f 2 "Across the Rockies" \
	"Driving through the Rockies." \
		/r/media/videos/EnRoute/Driving/TeslaToCA/AcrossTheRockies/*.mp4

addsm "Asilomar" \
	"A drone's view of the Asilomar Conference Center." \
			$SLOWSTAGE/Asilomar/*.mp4
addsm -s 935 "Asilomar Beach" \
	"A drone's view of the ocean near Asilomar." \
		$SLOWSTAGE/AsilomarBeach/*.mp4

# nice morning view:
# susie in the first shots. frame 30 is fine
addsm "Basin and Range" \
	"A drive through Nevada's basin-and-range region." \
		$SLOWSTAGE/BasinAndRange/*.mp4

# Needs to start at least after 41, 69 is goo
addsm -s 3 "Hana Road westbound" \
	"Drive west from Hana on Maui." \
		$SLOWSTAGE/HanaRoadWB/*.avi

addsm "It is flat" \
	"A drive through Kansas." \
		$SLOWSTAGE/ItsFlat/*.mp4

## original is time-lapsed
#addsm -f 660 "Westover to Sacramento" \
#	"Westover to Sacramento" \
#		$SLOWSTAGE/NearSacramento/*.mp4

addsm "Nevada to Davis via SAC" \
	"Nevada to Davis via SAC" \
		/r/media/videos/EnRoute/Driving/TeslaToCA/NevadaToDavis/*.mp4
addsm "Rockies Road" \
	"A drive through the Rockies." \
		$SLOWSTAGE/RockiesRoad/*.mp4
addsm "Into Utah" \
	"Driving from Colorado into Utah." \
		$SLOWSTAGE/ToUtah/*.mp4

TIME_LAPSE=$HOME/tmp/slowstage/timelapse

# long black frames at start:
addsm "Through the Adirondacks" \
	"Drive from the northern Adirondacks to NJ." \
		$TIME_LAPSE/adirondacks.mov

#./addsm "At the beach"			$TIME_LAPSE/beach.mpg
addsm "Bernardsville North" \
	"A drive near Bernardsville, NJ." \
		$TIME_LAPSE/bville-north-clip.mov
addsm "My Old Commute to FP" \
	"My old commute to work." \
		$TIME_LAPSE/commute.mov
addsm "Around Darien"	\
	"A drive around my old hometown, Darien, CT." \
		$TIME_LAPSE/darien.mov
addsm "Ellivesdranreb" \
	"A safe but confusing Sunday drive around the block." \
		$TIME_LAPSE/ellivsdranreb.mov

# boring, all cloudy
#./addsm "EWR to ORD test"		$TIME_LAPSE/ewr-ord-test.mov

addsm "Go west" "A flight to the west" $TIME_LAPSE/gowest.mov

# Needs higher res:
addsm "East from Key West" \
	"A drive to the mainland at Mach 1." \
		$TIME_LAPSE/key-west-east.mov
addsm "East from Key West second" \
	"Another version of the drive to the mainland at Mach 1." \
		$TIME_LAPSE/keys-eastbound.mov

# not very interesting
#./addsm "A lava lamp"			$TIME_LAPSE/lavalamp.mpeg
# poor video:
#./addsm "Moonrise in Nantucket"		$TIME_LAPSE/moonrise.mpeg

addsm "ORD to SFO test" \
	"The windowseat view from O'Hare to SFO." \
		$TIME_LAPSE/ord-sfo-test.mov
# poor resolution:
#addsm "Restroom" \
#	"An early timelapse of a public restroom area in Nantucket." \
#		$TIME_LAPSE/rest60.mpg
# original, from irix:
addsm "Restroom" \
	"An early timelapse of a public restroom area in Nantucket." \
		/r/media/videos/mv/rest60.mpg

# a test, but not interesting:
#./addsm "Reverse"			$TIME_LAPSE/reverse.mov
#./addsm "Slow"				$TIME_LAPSE/slow.mov

#./addsm "Fast solitaire" \
#	"Slowly." \
#		$TIME_LAPSE/solitaire.mov

ARCHIVES=$HOME/tmp/slowstage/archives
# really poor video, both seem identical
#./addsm -f 550 "Sand castle 0"			$ARCHIVES/castle0.mv
#./addsm "Sand castle 1"			$ARCHIVES/castle1.mv

# windowseat
WINDOWSEAT=$HOME/tmp/slowstage/windowseat/SFO-EWR
# not loaded yet
#./addsm "SFO-EWR, the windowseat"	$WINDOWSEAT/GOPR2216.MP4 $WINDOWSEAT/GO0*

indexsm
