#!/bin/sh
#
prog=fetchslowmovies
usage="usage: $prog"
#
#	Check the mother site for movies we don't have.

. ./slowdefs

case `uname` in
Linux)
	TMPDIR=${TMPDIR:-/var/tmp}
	;;
Darwin)
	TMPDIR=${TMPDIR:-/var/tmp}
	;;
FreeBSD)
	TMPDIR=${TMPDIR:-/var/tmp}
	;;
*)		# just guessing here
	TMPDIR=${TMPDIR:-/var/tmp}
esac

WRKDIR=$TMPDIR/slowmovies
mkdir -p $WRKDIR

mkdir -p $MOVIE_CATALOG	|| exit 1	# in case it is our first use

cd $MOVIE_LIB

curl -s "$MOVIE_LIST_URL" -o index || exit 2	# our list of movies

cat index |
while read line
do
	name=`echo "$line" | cut -f1 -d"	"`
	date=`echo "$line" | cut -f2 -d"	"`
	if [ -d catalog/"$name" ]
	then
		. catalog/"$name"/info
		if [ -a "$updated" -ge "$date" ]
		then
			echo "$prog: $name	up to date" 1>&2
			continue
		fi
	fi

	echo "$prog: $name	fetching..." 1>&2
	mkdir -p catalog/"$name"	|| exit 3
	rm -rf catalog/"$name"/*

	curl -s "$MOVIE_CATALOG_URL/$name/info" -o catalog/"$name"/info || {
		echo "$prog:	info missing, skipping" 1>&2
		continue
	}

	curl -s "$MOVIE_CATALOG_URL/$name/video.mp" -o catalog/"$name"/video.mp4 || {
		echo "$prog:	error, skipping" 1>&2
		continue
	}

	ls -l $MOVIE_CATALOG/"$name"
done
