#!/bin/sh
#
prog=indexsm
usage="$prog"
#
#	Update the index of the current slow movies

WEB_CATALOG=/r/media/slowmovies/catalog

cd $WEB_CATALOG

for i in *
do
	if [ -s "$i"/info ]
	then
		. "$i"/info	|| continue
		echo "$title	$updated"
	fi
done >../index
