#!/bin/sh
#
prog=indexsm
usage="$prog"
#
#	Update the index of the current slow movies

. slowdefs	|| exit 99

if [ ! -s $MASTER_SLOW_MEDIA_DIR/banner.png ]
then
	smbanner "Slow Movies" \
		"An experiment in calm drama\\\\by Bill Cheswick" \
		$MASTER_SLOW_MEDIA_DIR/banner.png	|| exit 20
fi

cd $MASTER_CATALOG_DIR

for i in *
do
	if [ -s "$i"/info ]
	then
		. "$i"/info	|| continue
		size=`du -s -m "$i" | awk '{print $1}'`
		echo "$title	$updated	$size"
	fi
done >$MASTER_SLOW_MEDIA_DIR/index
