#!/bin/sh
#
prog=playsm
usage="$prog m1 m2 ..."
#
#	Play a slow movie on the current machine.  There are a few styles:
#
#	desktop	desktop backround (x root, or equivalent)
#	full	full screen
#
#	We pick the best we can


export PATH=$PATH:$HOME/bin

. slowdefs

case `uname` in
Linux)
	TMPDIR=${TMPDIR:-/var/tmp}
	style=desktop
	;;
Darwin)
	TMPDIR=${TMPDIR:-/var/tmp}
	style=appledesktop
	;;
FreeBSD)
	TMPDIR=${TMPDIR:-/var/tmp}
	style=desktop
	;;
*)		# just guessing here
	TMPDIR=${TMPDIR:-/var/tmp}
	style=desktop
esac

WRKDIR=$TMPDIR/slowmovies
mkdir -p $WRKDIR
rm -rf $WRKDIR/*

cd $MOVIE_CATALOG

while [ $# -gt 0 ]
do
	movie="$1"

	if [ ! -d "$movie" ]
	then
		echo "$prog: $movie	missing" 1>&2
		continue
	fi

	. "$movie"/info

	if [ ! -n "$spf" ]
	then
		spf=10		# default six frames per minute
	fi

	echo "`date +%'b %e %H:%m:%S'`	$spf spf	$title" | tee -a $LOG 
	
	nice ffmpeg -i "$movie"/video.* -q:v 2 -v 16 \
		$WRKDIR/frame%09d.jpeg &

	sleep 1		# let ffmpeg start cracking

	fn=`cd $WRKDIR; ls | sed 1q`

	if [ ! -n $WRKDIR/$fn ]
	then
		echo "$prog:	apparent ffmpeg problem, aborting" 1>&2
		exit 2
	fi

	while [ -n "$WRKDIR/$fn" ]
	do
		case $style in
		desktop)
			xloadimage -fullscreen -onroot -quiet \
				-border black $WRKDIR/$fn
			;;
		appledesktop)
osascript <<!EOF
tell application "System Events"
        tell (every desktop)
                set picture rotation to 0
                set picture to POSIX file "$fn"
        end tell
end tell
!EOF
			;;
		full)
			xloadimage -fullscreen -border black $fn
			;;
		esac

		sleep $spf

		rm -f "$WRKDIR/$fn"
		fn=`cd $WRKDIR; ls | sed 1q`
	done
	wait
	ls -l $WRKDIR
	rm -rf $WRKDIR/*

	shift
done
