#!/bin/sh
#
prog=playsm
usage="$prog [-l] [-r] [-k] {[-a] | m1 m2 ...| -i i1,i2,i3,... }"
#
#	Play a slow movie on the current machine.  There are a few styles:
#
#	desktop	desktop backround (x root, or equivalent)
#	full	full screen
#
#	We pick the best we can.
#
#	-a	play all slowmovies
#	-n	play only new or revised movies
#	-l	list available slowmovies, and exit
#	-r	play desired movies in random order
#	-k	kill any current players on this machine

export PATH=$PATH:$HOME/bin

WRKDIR=${WRKDIR:-${TMPDIR}/${prog}}
CACHE=$WRKDIR/cache
mkdir -p $CACHE        || exit 100

. slowdefs	|| exit 99
. setupsm	|| exit 98

cd $LOCAL_MOVIE_CATALOG
	grep 'updated=[0-9]' */info |
	sed 's:/.*$::' >$WRKDIR/available_movies

>$WRKDIR/toplay

# only one player running, please

playsm_pid=`cat $WRKDIR/pid 2>/dev/null`
case "$playsm_pid" in
"")	;;
*)	npid=`ps -p $playsm_pid | sed -n '2,$p'`
	case "$rpid" in
	"")	# no longer running
		rm -f $WRKDIR/pid;;
	*)
		log "$prog:	already running"
		exit 1
	esac
esac

our_pid=$$
echo $our_pid >$WRKDIR/pid

randomize=
onlynew=

while [ $# -gt 0 ]
do
	case "$1" in
	-a)	cp $WRKDIR/available_movies $WRKDIR/toplay
		shift;;
	-i)	shift
		indexlist=`echo "$1" | tr ',' ' '`
		shift
		for i in $indexlist
		do
			movie_name=`sed -n ${i}p <$WRKDIR/available_movies`
			if [ -n "$movie_name" ]
			then
				echo "$movie_name" >>$WRKDIR/toplay
			fi
			shift
		done
		break;;
	-k)
		rm -f $WRKDIR/pid
		exit 0;;
	-l)	nl <$WRKDIR/available_movies
		exit 0
		;;
	-n)	onlynew=true
		shift;;
	-r)	randomize=true
		shift;;
	-*)	echo "$usage" 1>&2
		exit 1;;
	*)	for i in "$@"
		do
			echo "$i" >>$WRKDIR/toplay
		done
		break
	esac
done

(	cat $LOCAL_MOVIE_LIB/dontwatch 2>/dev/null
	if [ -n "$onlynew" ]
	then
		cat $LOCAL_MOVIE_LIB/viewed 2>/dev/null
	fi
) |
sort -u |
comm -23 $WRKDIR/toplay - >$WRKDIR/playlist


if [ -n "$randomize" ]
then
	awk <$WRKDIR/playlist '
		BEGIN {x = srand() }
			{print rand() "	" $0}
	' |
	sort -n |
	cut -d'	' -f2-
else
	cat $WRKDIR/playlist
fi | 
while read movie
do
	log "$prog: $movie"
	if [ ! -d "$movie" ]
	then
		log "$prog:	missing"
		continue
	fi

	. "$movie"/info

	if [ -s "$movie/banner.png" ]
	then
		show_frame "$movie/banner.png"
	fi

	if [ ! -n "$spf" ]
	then
		spf=10		# default six frames per minute
	fi

	lastcached=`sed 1q $WRKDIR/lastcached 2>/dev/null`
	if [ ! -n "$lastcached" -o "$lastcached" != "$movie" ]
	then
		log "$prog: 	cracking..."
		if ffmpeg -hide_banner -v 8 -i "$movie"/video.* -qscale:v 2 \
				$CACHE/frame%09d.jpeg 2>/dev/null
		then
			echo "$movie" >$WRKDIR/lastcached
			log "$prog:	`(cd $CACHE; ls | wc -l | tr -d ' ')` frames extracted"
		else
			rm -f $WRKDIR/lastcached
		fi
	else
		log "$prog: 	repeat, using cached frames"
	fi

	total_frames=`(cd $CACHE; ls | wc -l | tr -d ' ')`

	(cd $CACHE; ls) |
	case "$first" in		# skip leading frames, if desired
	"")	cat -;;
	0)	cat -;;
	*)	sed 1,${first}d
		log "$prog: 	skipping ${first} frames"
	esac |
	case $count in		# limit frame count, if desired
	"")	cat -;;
	all)	cat -;;
	*)	sed -n 1,${count}p
		log "$prog: 	limited to ${count} frames"
	esac |
	while read frame
	do
		if [ ! -s $WRKDIR/pid ]
		then
			log "$prog:	** terminated **"
			break
		elif [ `sed 1q $WRKDIR/pid` != $our_pid ]
		then
			log "$prog:	** Terminated **"
			break
		fi

		fn="$CACHE/$frame"
		show_frame "$fn"
		sleep $spf
	done

	log "$prog:	finished"
	echo "$movie" >>$LOCAL_MOVIE_LIB/viewed
done

log "$prog	exiting"
