#!/bin/sh
#
prog=prepmovie
usage="$prog movie-name staging-dir movie1 movie2 ..."
#
#	Prepare a movie for distribution to slowmovie clients.
#	This involves setting up a few simple files, and splitting
#	the movie into convenient chunks.  All this is written into
#	prepped-dir, which is created if it doesn't exist.

CHUNK_SIZE=300	# megabytes.  Split the movie into chunks this size

case $# in
0|1|2)
	echo "$usage" 1>&2
	exit 1;;
*)	name="$1";	shift
	pdir="$1";	shift
	;;
esac

src="$1"

DIR="$pdir"/"$name"
rm -rf $DIR/* 2>/dev/null

mkdir -p "$DIR" 2>/dev/null
STATS=$DIR/stats
INFO=$DIR/info

m=1
while [ $# -gt 0 ]
do
	src="$1";	shift
	echo "$prog:	source $src" 1>&2
	size=`ls -ldH "$src" | awk '{print $5}'` 
	echo "$prog:	Size: $size" 1>&2

	ffprobe -select_streams v -show_streams "$src" 2>/dev/null |
		grep '^[a-z].*=' |
		grep -v ' ' >${STATS}_$m
	chmod +x ${STATS}_$m

	. ${STATS}_$m

	echo "$prog:	Number of frames: $nb_frames" 1>&2
	echo "$prog:	Duration: $duration" 1>&2

	nchunks=`expr $size / ${CHUNK_SIZE}000000 + 1`
	echo "$prog:	Chunks: $nchunks" 1>&2

#	fpc=`awk "BEGIN {print int($nb_frames + 1.0 + ($nchunks - 1)/$nchunks)}"`
#	echo "$prog:	Frames/chunk: $fpc" 1>&2

	frame_list=`awk -v nframes=$nb_frames -v nchunks=$nchunks 'BEGIN {
		fpc = int((nframes + (nchunks - 1))/nchunks)
		cl=fpc
		for (i=2; i<nchunks; i++)
			cl = cl "," i*fpc
		print cl
		exit
	}'`
	echo "$prog:	Frame list: $frame_list" 1>&2

	ffmpeg -i $src -map 0:0 -c:v mpeg4 -preset slow -crf 18 -f segment \
			-segment_frames $frame_list "$DIR"/"${m}_%03d.mp4" </dev/null ||
		break
	m=`expr $m + 1`
done
