#!/bin/sh
#
prog=smadd
usage="$prog [-s spf] [-f first_frame] [-n frame_count] [-F] [-q quality] title subtitle i1 i2 ..."
#
#	Add a movie named "name" to our catalog.  It consists of one or
#	more video files found relative to the current directory, and
#	concatentated together.
#
#	If that directory contains an audio.mp3 file, that is added also.
#
#	files, each of which may have additional information in a .data file.
#	All are processed into the catalog directory, if forced or the catalog
#	entry is missing or older.
#
#	Careful with those quotes: these titles usually contain spaces. Tabs
#	are our field separators.
#
#	-F	force rebuild of given movies

. smdefs	|| exit 99

nspf=10
nfirst=0
ncount=all
nforce=
nquality=

while [ $# -gt 0 ]
do
	case "$1" in
	-s)	shift; nspf=$1; shift;;
	-f)	shift; nfirst=$1; shift;;
	-F)	shift; nforce=true;;
	-n)	shift; ncount=$1; shift;;
	-q)	shift; nquality=$1; shift;;
	-*)	echo "$usage" 1>&2
		exit 1;;
	*)	break
	esac
done

if [ $# -lt 3 ]
then
	echo "usage: $usage" 1>&2
	exit 1
fi

title="$1";	shift
subtitle="$1";	shift

set -x

inputlist=""
first_video_fn="$1"

while [ $# -gt 0 ]
do
	inputlist="$inputlist -i '$1'"
	shift
done

mkdir -p "$MASTER_CATALOG_DIR/$title"
cd "$MASTER_CATALOG_DIR/$title"

if [ ! -s banner.png ]
then
	smbanner "$title" "$subtitle"  banner.png
fi

video_dir=`dirname "$first_video_fn"`
audio_file="$video_dir"/audio.mp3

if [ ! -s "$audio_file" ]
then
	video_base=`echo "$first_video_fn" | sed 's/\.[a-z]*$//'`
	audio_file="$video_base".mp3
	if [ ! -s "$audio_file" ]
	then
		audio_file=""
	fi
fi

if [ -n "$audio_file" ]
then
	if [ -n "$force" -o ! -s audio.mp3 -o "$audio_file" -nt audio.mp3 ]
	then
		echo "$prog:	$title	updating audio file" 1>&2
		cp "$audio_file"  audio.mp3
		audio_updated=`date +%s`
	fi
fi


if [ -n "$force" -o ! -s info -o ! -s video.mp4  ]
then
	echo "$prog:	$title		building ..." 1>&2
	#ffmpeg $inputlist -y -v 16  \
echo =====ffmpeg $inputlist -y -q:v 2 -v 16 -huffman optimal====
	eval "ffmpeg $inputlist -y -q:v 2 -v 16 -huffman optimal \
		-vf "drawtext=text='$title': \
			fontcolor=white: fontsize=20: \
			box=1: boxcolor=black@0.5: \
			fix_bounds=1: \
			boxborderw=5: x=5: y=h-22:, \
		drawtext=text='frame %{n}': \
			fontcolor=white: fontsize=16: \
			box=1: boxcolor=black@0.5: \
			fix_bounds=1: \
			boxborderw=5: x=w-tw-5: y=h-18:" \
		video.mp4" || {
			rm -f info
			echo "	error, aborting" 1>&2
			exit 10
		}
	updated=`date +%s`
else
	echo "$prog:	$title		updating info ..." 1>&2
	. ./info
	if [ ! -n "$updated" ]
	then
		updated=`stat -f%m video.mp4`
	fi
fi

# generate new info file

if [ ! -n "$updated" ]
then
	updated=`date +%s`
fi

cat <<!EOF >info
title="$title"
spf=$nspf
first=$nfirst
count=$ncount
quality=$nquality
updated=$updated
audio_updated=$audio_updated
subtitle="$subtitle"
!EOF
chmod +x info

smindex
