#!/bin/sh
#
prog=smcreate
usage="$prog [-F]"
#
#	(re)install all our movies, or the ones that are new or changed.
#
#	-F	force rebuild of all

force=
while [ $# -gt 0 ]
do
	case "$1" in
	-F)	shift; force="-F";;
	-*)	echo "$usage" 1>&2
		exit 1;;
	*)	break
	esac
done

if [ $# -gt 0 ]
then
	echo "$usage" 1>&2
	exit 1
fi

. smdefs	|| exit 99

if [ -n "$force" ]
then
	cd $MASTER_CATALOG_DIR	|| exit 10
	rm -f */info
	echo "$prog: all slow movies disabled" 1>&2
fi

SLOWSTAGE=$HOME/tmp/slowstage

TIME_LAPSE=$HOME/tmp/slowstage/timelapse


smadd -q 4 "Pool rain" \
        "Spring rain in a swimming pool" \
                /r/media/videos/Etc/RainInThePool/GOPR4123.MP4

# long black frames at start:
smadd -q 3 "Leaving the Adirondacks" \
	"An evening's departure from Sabbatis to points south." \
		$TIME_LAPSE/adirondacks.mov

smadd -s 3 -q 2 "Surfside sunset" \
	"Surfside sunset" \
		/r/media/videos/ACK/Surfside/sunset-raw/*.MP4

# Needs to start at least after 41, 69 is good
smadd -f 41 -q 3 "Hana Road westbound" \
	"24 times slower." \
		$SLOWSTAGE/HanaRoadWB/*.avi

## surfside beach ##

smadd -q 2 "Sand castle 1" \
	"Ches sandcastle in a tidal pool" \
		/r/media/videos/ACK/Surfside/castle-1/*.MP4

smadd -q 4 "Sand castle 2" \
	"Ches sandcastle in a tidal pool" \
		/r/media/videos/ACK/Surfside/castle-2/*.MP4

smadd -q 5 "Surfside beach" \
	"Surfside beach" \
		/r/media/videos/ACK/Surfside/wet-1.MP4

smadd -f 700 -q 4 "Surfside beach surf" \
	"Surfside beach surf" \
		/r/media/videos/ACK/Surfside/wet-2.MP4

smadd "Surfside beach pool" \
        "Surfside beach pool" \
                /r/media/videos/ACK/Surfside/wet-3/wet3-[ab].MP4

smadd -f 200 -q 5 "NJ-approved firework" \
	"Now that fireworks are legal in NJ, we can watch one." \
		/r/media/videos/Fireworks/NJFireworksLarge.mp4

smadd -q 2 "2011 fireworks" \
	"A fireworks display from 2011 at the Somerset Hills Gold course." \
		/r/media/videos/Fireworks/fireworks2011-[12].mp4

smadd -q 2 "Mousecam" \
	"A mouse investigates a Have-A-Heart trap, under infrared lighting." \
		/r/media/videos/Etc/mousecam.mpg

smadd -f 3 -q 2 "Across the Rockies" \
	"Driving through the Rockies." \
		/r/media/videos/EnRoute/Driving/TeslaToCA/AcrossTheRockies/*.mp4

smadd -q 3 "Asilomar" \
	"A drone's view of the Asilomar Conference Center." \
			$SLOWSTAGE/Asilomar/*.mp4
smadd -q 3 -s 935 "Asilomar Beach" \
	"A drone's view of the ocean near Asilomar." \
		$SLOWSTAGE/AsilomarBeach/*.mp4

# nice morning view:
# susie in the first shots. frame 30 is fine
smadd -q 4 "Moab to Canyonlands" \
	"A sunrise trip to the Canyonlands lookup" \
		$SLOWSTAGE/MoabToCanyonlands/*.mp4

smadd -q 2 "It is flat" \
	"Timelapse drive through Kansas." \
		$SLOWSTAGE/ItsFlat/*.mp4

## original is time-lapsed
#smadd -f 660 "Westover to Sacramento" \
#	"Westover to Sacramento" \
#		$SLOWSTAGE/NearSacramento/*.mp4

smadd -q 3 "Nevada to Davis via SAC" \
	"Nevada to Davis via SAC" \
		/r/media/videos/EnRoute/Driving/TeslaToCA/NevadaToDavis/*.mp4
smadd -q 3 "Rockies Road" \
	"A drive into the Rockies." \
		$SLOWSTAGE/RockiesRoad/*.mp4
smadd -q 3 "Into Utah" \
	"Time lapse driving from Colorado into Utah." \
		$SLOWSTAGE/ToUtah/*.mp4

# old time lapse, 4x3, terry sand castles
smadd -q 3 "Early sand castles" \
	"Terry castles in a tidal pool" \
		$TIME_LAPSE/beach.mpg
smadd -q 2 "I-287 North" \
	"A high-speed drive on I-287 north to I-87." \
		$TIME_LAPSE/bville-north-clip.mov
smadd -q 2 "My Old Commute to FP" \
	"My old commute to work." \
		$TIME_LAPSE/commute.mov
# no, not Darien. North from bville:
#smadd "Around Darien"	\
#	"A drive around my old hometown, Darien, CT." \
#		$TIME_LAPSE/darien.mov

smadd -q 4 "Ellivesdranreb" \
	"A safe but confusing Sunday drive around the block." \
		$TIME_LAPSE/ellivsdranreb.mov

# boring, all cloudy
smadd -q 0 "EWR to ORD test" ""		$TIME_LAPSE/ewr-ord-test.mov

smadd -q 2 "West over the Sierras" \
	"Time lapse window seat into the bay area" \
		 $TIME_LAPSE/gowest.mov

# Needs higher res:
# not the whole deal
#smadd "East from Key West" \
#	"A drive to the mainland at Mach 1." \
#		$TIME_LAPSE/key-west-east.mov

smadd -q 3 "From Key West to the Mainland at Mach 20" \
	"" \
		$TIME_LAPSE/keys-eastbound.mov

# not very interesting
#./smadd "A lava lamp"			$TIME_LAPSE/lavalamp.mpeg
# poor video:
#./smadd "Moonrise in Nantucket"		$TIME_LAPSE/moonrise.mpeg

smadd -q 2 "ORD to SFO test" \
	"The windowseat view from O'Hare to SFO." \
		$TIME_LAPSE/ord-sfo-test.mov
# poor resolution:
#smadd "Restroom" \
#	"An early timelapse of a public restroom area in Nantucket." \
#		$TIME_LAPSE/rest60.mpg
# original, from irix:
smadd -q 1 "Restroom" \
	"An early timelapse of a public restroom area in Nantucket." \
		/r/media/videos/mv/rest60.mpg

# a test, but not interesting:
#./smadd "Reverse"			$TIME_LAPSE/reverse.mov
smadd -q 1 "iChat" "T and K on iChat"	$TIME_LAPSE/slow.mov

#./smadd "Fast solitaire" \
#	"Slowly." \
#		$TIME_LAPSE/solitaire.mov

ARCHIVES=$HOME/tmp/slowstage/archives
# really poor video, both seem identical
#./smadd -f 550 "Sand castle 0"			$ARCHIVES/castle0.mv
#./smadd "Sand castle 1"			$ARCHIVES/castle1.mv

# windowseat
WINDOWSEAT=$HOME/tmp/slowstage/windowseat/SFO-EWR
# not loaded yet
#./smadd "SFO-EWR, the windowseat"	$WINDOWSEAT/GOPR2216.MP4 $WINDOWSEAT/GO0*

smindex -s

