#!/bin/sh
#
prog=sminstall
usage=$prog
#
#	Install the slowmovie software on Raspberry Pi running Debian,
#	FreeBSD machines, and MacOS.

BIN=$HOME/bin

if [ ! -d $BIN ]
then
	mkdir -p ${BIN}	|| exit 1
fi

progs="smadd smupdate smplay smindex smbanner smstart \
	sminstall smsysinstall smsetup smcreate smdefs"

for i in $progs
do
	if [ ! -s $BIN/$i -o $i -nt $BIN/$i ]
	then
		cp $i $BIN/$i	|| exit 2
	fi
done

# Set up .xinitrc to start up things

if ! grep 'smstart' $HOME/.xinitrc >/dev/null 2>/dev/null
then
	cat <<!EOF >$HOME/.xinitrc
#!/bin/sh

exec >>/tmp/xout 2>>/tmp/xerr

xsetroot -solid darkblue -cursor_name top_left_arrow
xset s off -dpms

smstart -r -a -n &

exec w9wm -term xterm
!EOF
fi

# add x start to .profile

if ! grep startx $HOME/.profile >/dev/null
then
	cat <<!EOF >>$HOME/.profile

export  PATH=$PATH:$HOME/bin

case \`tty\` in
/dev/tty1)      startx -- ;; # -nocursor;;
esac
!EOF
fi

. ./smdefs	|| exit 99

if [ ! -s $LOG ]
then
	sudo cp /dev/null $LOG
	user=`id -u -n`
	sudo chown $user $LOG
	chmod 644 $LOG
fi

mkdir -p $LOCAL_MOVIE_CATALOG	|| exit 3
