#!/bin/sh
#
prog=sminstall
usage=$prog
#
#	Install the slowmovie software on Raspberry Pi running Debian,
#	FreeBSD machines, and MacOS.

BIN=$HOME/bin

if [ ! -d $BIN ]
then
	mkdir -p ${BIN}	|| exit 1
fi

for p in ffmpeg xloadimage w9wm xterm
do
	if [ ! -n `which $p` ]
	then
		case `uname` in
		Linux)
			sudo apt-get install -y $p	|| exit 10
			;;
		FreeBSD)
			sudo sudo pkg -y install $p
			;;
		Darwin)
			# stub
			;;
		esac
	fi
done

progs="addsm updatesm playsm playallsm indexsm slowdefs"

for i in $progs
do
	if [ ! -s $BIN/$i -o $i -nt $BIN/$i ]
	then
		cp $i $BIN/$i	|| exit 2
	fi
done

if [ ! -s $HOME/.xinitrc ]
then
	cat <<!EOF >$HOME/.xinitrc
#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/usr/local/lib/X11/xinit/.Xresources
sysmodmap=/usr/local/lib/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    xmodmap $usermodmap
fi

xsetroot -solid darkblue -cursor_name top_left_arrow
exec w9wm -term xterm
!EOF
fi

grep startx $HOME/.profile >/dev/null ||
	echo startx >>$HOME/.profile

. slowdefs

if [ ! -s $LOG ]
then
	sudo cp /dev/null $LOG
	user=`id -u -n`
	sudo chown $user $LOG
	chmod 644 $LOG
fi

mkdir -p $MOVIE_LIB/catalog	|| exit 3
