#!/bin/sh
#
prog=smstart
usage="$prog [smplay-params]"
#
#	Default: play everything we haven't seen before, randomly

. smdefs	|| exit 99

if [ -s $LOCAL_MOVIE_LIB/banner.png ]	# show sm logo page
then
	show_frame $LOCAL_MOVIE_LIB/banner.png
fi

case $# in
0)	smplay -a -r -n;;
*)	smplay "$@"
esac

