#!/bin/sh
#
prog=smsysinstall
usage=$prog
#
#	Try to load the various libraries we need to use our stuff.
#	This can be brittle.

BIN=$HOME/bin

if [ ! -d $BIN ]
then
	mkdir -p ${BIN}	|| exit 1
fi

case `uname` in
Linux)
	if [ ! -n "`which ffmpeg`" ]	# this is for av
	then
		sudo apt-get install -y libav-tools libavutil-dev \
			libavfilter-dev libavformat-dev libavcodec-dev libswscale-dev
	fi

	if [ ! -n "`which display`" ]
	then
		sudo apt-get install -y imagemagick
	fi

	for p in wget mpg123 bc xterm w9wm
	do
		if [ ! -n "`which $p`" ]
		then
			sudo apt-get install -y $p
		fi
	done

	splitter=ss
	;;
FreeBSD)
	for p in ffmpeg mpg123 xterm w9wm wget
	do
		if [ -z `which $p` ]
		then
			echo "$prog: install $p" 1>&2
			sudo port install $p
		fi
	done
	splitter=ss
	;;
Darwin)
	for p in ffmpeg mpg123
	do
		if [ -z `which $p` ]
		then
			echo "$prog: install $p" 1>&2
			sudo port install $p
		fi
	done
	splitter=ss
	;;
*)
	exit 16
esac
