#!/bin/sh
#
prog=setup_pi
usage="$prog"
#
# Build all the stuff that the current user needs to start showing slowmovies

BIN=$HOME/bin
if [ ! -d $BIN ]
then
	mkdir $BIN	|| exit 1
fi

# We need a bunch of software loaded into the system.  Start by getting the slowmovies repo

if which git >/dev/null
then
	:
else
	sudo apt-get -y install git
fi

if [ ! -d slowmovies ]
then
	git clone https://github.com/wcheswick/slowmovies.git	|| exit 10
fi
