#!/bin/sh
#
prog=surfside
usage="usage: $prog [-r] [-?] [movie]"
#
#	Continue watching the beach at Surfside, very slowly
#
#	-r resets to the start
#	=? lists movie directory contents

RATE=10		# seconds/frame

MOVIEDIR=$HOME/lib/Movies

SCENE=$MOVIEDIR/3/GOPR2222.MP4
SCENE=$MOVIEDIR/wet-2.mov

TMP=/tmp/$prog
LAST=$TMP/last_frame

case $1 in
-r)	rm -f $LAST; shift;;
-?)	ls -l $MOVIEDIR/*;
	exit 0;;
-*)	echo "$usage" 1>&2
	exit 1
esac

case $# in
0)	;;
1)	SCENE=$MOVIEDIR/$1;	shift;;
*)	echo "$usage" 1>&2
	exit 2
esac

mkdir -p $TMP
if [ ! -s $LAST ]
then
	last=0
	echo $last >$LAST
else
	last=`sed 1q $LAST`
fi

splitmovie -r $RATE -s $last $SCENE /tmp/surfside |
while read fn
do
	setwallpaper "$fn"
	last=`expr $last + 1`
	echo $last >$LAST

#	rm -f "$fn"
done
