#!/bin/sh
#
prog=slowclock
usage="$prog"
#
#	Update the time shown on the slow movie


. slowdefs

time=`date +%H:%M`
pbmtextps -font FreeSansBold -fontsize 72 "$time" |
	pnmcrop -white  >/tmp/slow.tmp &&
	mv /tmp/slow.tmp $CLOCK
